POST http://localhost:3000/api/v1/books
Content-Type: application/json

{
"book": {
  "title": "Harry Potter 20",
  "author_id": 3
 }
}

### GET ALL BOOKS
GET http://localhost:3000/api/v1/books
Authorization: Bearer eyJhbGciOiIUzI1NiJ9.eyJ1c2VyX2lkIjoyMCwiZXhwIjoiMTcxMjg2NzE5OSJ9.E2bhcjKzw9B2nymnJN-19rN-iyLEUwkFDjBXPFQ6gLc


### Get A Book
GET http://localhost:3000/api/v1/books/2

### Sign in
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "beniyoke@gmail.com",
  "password": "er"
}

### Sign Up
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "user": {
    "name": "John Doe",
    "email": "johndoe@example.com",
    "phone": "1234567890",
    "password": "secretpassword",
    "password_confirmation": "secretpassword"
  }
}